import sqlite3 as sql

def createDB():
    conn = sql.connect("plants.db")
    conn.commit()
    conn.close()

def createTable():
    conn = sql.connect("plants.db")
    cursor = conn.cursor()
    cursor.execute(
        """CREATE TABLE plants (
        id INTEGER PRIMARY KEY,
        title TEXT,
        description TEXT,
        descriptionEnvironment TEXT,
        image TEXT,
        invasive BOOLEAN,
        native BOOLEAN,
        exotic BOOLEAN, 
        caracteristic TEXT,
        soil TEXT,
        environment TEXT
        )"""
    )
    conn.commit()
    conn.close()

    
def insertRow(id, title, description, descriptionEnvironment, image, invasive, native, exotic, caracteristic, soil, environment):
    conn = sql.connect("plants.db")
    cursor = conn.cursor()
    instruccion = f"INSERT INTO plants VALUES ({id}, '{title}', '{description}', '{descriptionEnvironment}', '{image}', {invasive}, {native}, {exotic}, '{caracteristic}', '{soil}', '{environment}')"
    cursor.execute(instruccion)
    conn.commit()
    conn.close()

if __name__ == "__main__":
    createDB()
    createTable()
    insertRow(1, 'Diente de León', 'El diente de león es una planta herbácea de la familia de las asteráceas. Se encuentra en prados y campos abiertos, siendo común en primavera.', 'Se encuentra en prados y campos abiertos, siendo común en primavera.', '/imagenes/plantas/diente-de-leon.png', False, True, False, 'prados', 'arcilloso', 'prados: True, campos: True, jardines: False, costa: False, interior: False, montaña: False' )
    insertRow(2, 'Margarita', 'La margarita es una planta herbácea perenne de la familia de las asteráceas. Tiene flores blancas y se utiliza en jardinería y ornamentación.', 'Tiene flores blancas y se utiliza en jardinería y ornamentación.', '/imagenes/plantas/margarita.png', False, False, True, 'jardinería', 'arcilloso', 'prados: True, campos: True, jardines: True, costa: True, interior: True, montaña: True')
    insertRow(3, 'Lino', 'El lino es una planta herbácea anual de la familia de las lináceas. Se cultiva por sus fibras, que se utilizan en la industria textil.', 'Se cultiva por sus fibras, que se utilizan en la industria textil.', '/imagenes/plantas/lino.png', False, False, False, 'textil', 'arcilloso', 'prados: True, campos: True, jardines: True, costa: False, interior: False, montaña: False')
    insertRow(4, 'Malva', 'La malva es una planta herbácea perenne de la familia de las malváceas. Tiene flores rosadas y se utiliza en jardinería y medicina tradicional.', 'Tiene flores rosadas y se utiliza en jardinería y medicina tradicional.', '/imagenes/plantas/malva.png', False, False, True, 'jardinería', 'arcilloso', 'prados: True, campos: True, jardines: True, costa: True, interior: True, montaña: True')
    insertRow(5, 'Achicoria', 'La achicoria es una planta herbácea bienal de la familia de las asteráceas. Se cultiva por sus hojas, que se utilizan en alimentación humana.', 'Se cultiva por sus hojas, que se utilizan en alimentación humana.', '/imagenes/plantas/achicoria.png', False, False, False, 'alimentación', 'arcilloso', 'prados: True, campos: True, jardines: True, costa: False, interior: False, montaña: False')
    insertRow(6, 'Zarzaparrilla', 'La zarzaparrilla es una planta trepadora de la familia de las smiláceas. Tiene propiedades medicinales y se utiliza en la medicina tradicional.', 'Tiene propiedades medicinales y se utiliza en la medicina tradicional.', '/imagenes/plantas/zarzaparrilla.png', False, False, True, 'medicinal', 'arcilloso', 'prados: False, campos: False, jardines: True, costa: False, interior: True, montaña: True')
    insertRow(7, 'Madreselva', 'La madreselva es una planta trepadora de la familia de las caprifoliáceas. Tiene flores fragantes y se utiliza en jardinería y ornamentación.', 'Tiene flores fragantes y se utiliza en jardinería y ornamentación.', '/imagenes/plantas/madreselva.png', False, False, True, 'jardinería', 'arcilloso', 'prados: False, campos: False, jardines: True, costa: True, interior: True, montaña: True')
    insertRow(8, 'Tamarix', 'El tamarix es un arbusto o árbol de la familia de las tamaricáceas. Tiene flores rosadas y se utiliza en jardinería y ornamentación.', 'Tiene flores rosadas y se utiliza en jardinería y ornamentación.', '/imagenes/plantas/tamarix.png', False, False, True, 'jardinería', 'arcilloso', 'prados: False, campos: False, jardines: True, costa: True, interior: True, montaña: True')
    insertRow(9, 'Pino de Monterrey', 'El pino de Monterrey es un árbol de la familia de las pináceas. Tiene hojas perennes en forma de aguja y se utiliza en jardinería y forestación.', 'Tiene hojas perennes en forma de aguja y se utiliza en jardinería y forestación.', '/imagenes/plantas/pino-de-monterrey.png', False, False, True, 'jardinería', 'arcilloso', 'prados: False, campos: False, jardines: True, costa: True, interior: True, montaña: True')
    insertRow(10, 'Plumero Pampeano', 'El plumero pampeano es una planta herbácea perenne de la familia de las asteráceas. Tiene flores rosadas y se utiliza en jardinería y ornamentación.', 'Tiene flores rosadas y se utiliza en jardinería y ornamentación.', '/imagenes/plantas/plumero-pampeano.png', False, False, True, 'jardinería', 'arcilloso', 'prados: True, campos: True, jardines: True, costa: True, interior: True, montaña: True')
    insertRow(11, 'Uña de Gato', 'La uña de gato es una planta trepadora de la familia de las rubiáceas. Tiene propiedades medicinales y se utiliza en la medicina tradicional.', 'Tiene propiedades medicinales y se utiliza en la medicina tradicional.', '/imagenes/plantas/una-de-gato.png', False, False, True, 'medicinal', 'arcilloso', 'prados: False, campos: False, jardines: True, costa: False, interior: True, montaña: True')
    insertRow(12, 'Valeriana Roja', 'La valeriana roja es una planta herbácea perenne de la familia de las valerianáceas. Tiene propiedades medicinales y se utiliza en la medicina tradicional.', 'Tiene propiedades medicinales y se utiliza en la medicina tradicional.', '/imagenes/plantas/valeriana-roja.png', False, False, True, 'medicinal', 'arcilloso', 'prados: True, campos: True, jardines: True, costa: False, interior: True, montaña: True')
    insertRow(13, 'Vinca Pervinca', 'La vinca pervinca es una planta herbácea perenne de la familia de las apocináceas. Tiene flores azules o violetas y se utiliza en jardinería y ornamentación.', 'Tiene flores azules o violetas y se utiliza en jardinería y ornamentación.', '/imagenes/plantas/vinca-pervinca.png', False, False, True, 'jardinería', 'arcilloso', 'prados: True, campos: True, jardines: True, costa: True, interior: True, montaña: True')
    insertRow(14, 'Cerraja', 'La cerraja es una planta herbácea anual de la familia de las asteráceas. Se cultiva por sus hojas, que se utilizan en alimentación humana.', 'Se cultiva por sus hojas, que se utilizan en alimentación humana.', '/imagenes/plantas/cerraja.png', False, False, False, 'alimentación', 'arcilloso', 'prados: True, campos: True, jardines: True, costa: False, interior: False, montaña: False')
    insertRow(15, 'Rábano Silvestre', 'El rábano silvestre es una planta herbácea anual de la familia de las brassicáceas. Se cultiva por su raíz, que se utiliza en alimentación humana.', 'Se cultiva por su raíz, que se utiliza en alimentación humana.', '/imagenes/plantas/rábano-silvestre.png', False, False, False, 'alimentación', 'arcilloso', 'prados: True, campos: True, jardines: True, costa: False, interior: False, montaña: False')
    insertRow(16, 'Argoma', 'La argoma es una planta arbustiva de la familia de las fabáceas. Se utiliza en jardinería y ornamentación.', 'Se utiliza en jardinería y ornamentación.', '/imagenes/plantas/argoma.png', False, False, False, 'jardinería', 'arcilloso', 'prados: False, campos: False, jardines: True, costa: True, interior: True, montaña: True')
    insertRow(17, 'Brezo', 'El brezo es un arbusto de la familia de las ericáceas. Tiene flores rosadas y se utiliza en jardinería y ornamentación.', 'Tiene flores rosadas y se utiliza en jardinería y ornamentación.', '/imagenes/plantas/brezo.png', False, False, False, 'jardinería', 'arcilloso', 'prados: False, campos: False, jardines: True, costa: True, interior: True, montaña: True')
    insertRow(18, 'Trébol Morado', 'El trébol morado es una planta herbácea perenne de la familia de las fabáceas. Se utiliza en jardinería y ornamentación.', 'Se utiliza en jardinería y ornamentación.', '/imagenes/plantas/trébol-morado.png', False, False, False, 'jardinería', 'arcilloso', 'prados: True, campos: True, jardines: True, costa: True, interior: True, montaña: True')
    insertRow(19, 'Pulmonaria', 'La pulmonaria es una planta herbácea perenne de la familia de las boragináceas. Tiene flores rosadas o azules y se utiliza en jardinería y ornamentación.', 'Tiene flores rosadas o azules y se utiliza en jardinería y ornamentación.', '/imagenes/plantas/pulmonaria.png', False, False, False, 'jardinería', 'arcilloso', 'prados: True, campos: True, jardines: True, costa: True, interior: True, montaña: True')
    insertRow(20, 'Roble', 'El roble es un árbol caducifolio de la familia de las fagáceas. Se utiliza en carpintería y ebanistería por su madera resistente.', 'Se utiliza en carpintería y ebanistería por su madera resistente.', '/imagenes/plantas/roble.png', False, True, False, 'madera', 'arcilloso', 'prados: False, campos: False, jardines: True, costa: False, interior: True, montaña: True')
    insertRow(21, 'Haya', 'La haya es un árbol caducifolio de la familia de las fagáceas. Se utiliza en carpintería y ebanistería por su madera dura.', 'Se utiliza en carpintería y ebanistería por su madera dura.', '/imagenes/plantas/haya.png', False, True, False, 'madera', 'arcilloso', 'prados: False, campos: false, jardines: true, costa: false, interior: true, montaña: true')
    insertRow(22, 'Enebro', 'El enebro es un arbusto perenne de la familia de las cupresáceas. Tiene frutos comestibles y se utiliza en la elaboración de gin.', 'Tiene frutos comestibles y se utiliza en la elaboración de gin.', '/imagenes/plantas/enebro.png', False, True, False, 'gin', 'arenoso', 'prados: false, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(23, 'Tilo', 'El tilo es un árbol caducifolio de la familia de las tiliáceas. Tiene flores fragantes y se utiliza en jardinería y ornamentación.', 'Tiene flores fragantes y se utiliza en jardinería y ornamentación.', '/imagenes/plantas/tilo.png', False, True, False, 'jardinería', 'arcilloso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(24, 'Acebo', 'El acebo es un arbusto perenne de la familia de las aquifoliáceas. Tiene bayas rojas y se utiliza en jardinería y ornamentación.', 'Tiene bayas rojas y se utiliza en jardinería y ornamentación.', '/imagenes/plantas/acebo.png', False, True, False, 'jardinería', 'arcilloso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(25, 'Lavanda', 'La lavanda es un arbusto aromático de la familia de las lamiáceas. Tiene flores moradas y se utiliza en perfumería y cosmética.', 'Tiene flores moradas y se utiliza en perfumería y cosmética.', '/imagenes/plantas/lavanda.png', False, False, True, 'perfumería', 'arenoso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(26, 'Romero', 'El romero es un arbusto aromático de la familia de las lamiáceas. Tiene hojas aromáticas y se utiliza en la cocina y la medicina tradicional.', 'Tiene hojas aromáticas y se utiliza en la cocina y la medicina tradicional.', '/imagenes/plantas/romero.png', False, False, True, 'cocina', 'arenoso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(27, 'Helecho', 'El helecho es una planta ornamental de la familia de las pteridáceas. Tiene hojas verdes y se utiliza en jardinería y ornamentación.', 'Tiene hojas verdes y se utiliza en jardinería y ornamentación.', '/imagenes/plantas/helecho.png', False, False, False, 'jardinería', 'arcilloso', 'prados: false, campos: false, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(28, 'Alcachofa', 'La alcachofa es una planta herbácea perenne de la familia de las asteráceas. Se cultiva por sus cabezas florales, que se utilizan en alimentación humana.', 'Se cultiva por sus cabezas florales, que se utilizan en alimentación humana.', '/imagenes/plantas/alcachofa.png', False, False, False, 'alimentación', 'arcilloso', 'prados: true, campos: true, jardines: true, costa: false, interior: false, montaña: false')
    insertRow(29, 'Clemátide', 'La clemátide es una planta trepadora de la familia de las ranunculáceas. Tiene flores llamativas y se utiliza en jardinería y ornamentación.', 'Tiene flores llamativas y se utiliza en jardinería y ornamentación.', '/imagenes/plantas/clematide.png', False, False, False, 'jardinería', 'arcilloso', 'prados: false, campos: false, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(30, 'Hierba de San Juan', 'La Hierba de San Juan es una planta herbácea de la familia de las hipericáceas. Tiene propiedades medicinales y se utiliza en fitoterapia.', 'Tiene propiedades medicinales y se utiliza en fitoterapia.', '/imagenes/plantas/hierba-de-san-juan.png', False, True, False, 'fitoterapia', 'arenoso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(31, 'Perejil Gigante', 'El perejil gigante es una hierba aromática de la familia Apiaceae. Tiene hojas grandes y se utiliza en gastronomía y medicina.', 'Tiene hojas grandes y se utiliza en gastronomía y medicina.', '/imagenes/plantas/perejil-gigante.png', False, False, False, 'gastronomía', 'arcilloso', 'prados: false, campos: true, jardines: true, costa: true, interior: true, montaña: false')
    insertRow(32, 'Menta', 'La menta es una planta aromática de la familia de las lamiáceas. Tiene hojas fragantes y se utiliza en gastronomía, perfumería y medicina.', 'Tiene hojas fragantes y se utiliza en gastronomía, perfumería y medicina.', '/imagenes/plantas/menta.png', False, False, False, 'gastronomía', 'arcilloso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(33, 'Hierbabuena', 'La hierbabuena es una planta aromática de la familia de las lamiáceas. Tiene hojas aromáticas y se utiliza en gastronomía y medicina.', 'Tiene hojas aromáticas y se utiliza en gastronomía y medicina.', '/imagenes/plantas/hierbabuena.png', False, False, False, 'gastronomía', 'arcilloso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(34, 'Pino Silvestre', 'El pino silvestre es un árbol perenne de la familia de las pináceas. Tiene hojas aciculares y se utiliza en carpintería y ebanistería.', 'Tiene hojas aciculares y se utiliza en carpintería y ebanistería.', '/imagenes/plantas/pino-silvestre.png', False, True, False, 'carpintería', 'arenoso', 'prados: false, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(35, 'Llantén', 'El llantén es una planta herbácea de la familia de las plantagináceas. Tiene hojas lanceoladas y se utiliza en medicina tradicional.', 'Tiene hojas lanceoladas y se utiliza en medicina tradicional.', '/imagenes/plantas/llanten.png', False, False, False, 'medicina', 'arcilloso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(36, 'Cardo', 'El cardo es una planta herbácea de la familia de las asteráceas. Tiene propiedades medicinales y se utiliza en fitoterapia.', 'Tiene propiedades medicinales y se utiliza en fitoterapia.', '/imagenes/plantas/cardo.png', False, False, False, 'fitoterapia', 'arcilloso', 'prados: true, campos: true, jardines: true, costa: false, interior: false, montaña: false')
    insertRow(37, 'Saúco', 'El saúco es un arbusto perenne de la familia de las adoxáceas. Tiene flores blancas y se utiliza en gastronomía y medicina tradicional.', 'Tiene flores blancas y se utiliza en gastronomía y medicina tradicional.', '/imagenes/plantas/sauco.png', False, False, False, 'gastronomía', 'arcilloso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(38, 'Tulipán', 'El tulipán es una planta bulbosa de la familia de las liliáceas. Tiene flores llamativas y se utiliza en jardinería y floricultura.', 'Tiene flores llamativas y se utiliza en jardinería y floricultura.', '/imagenes/plantas/tulipan.png', False, False, True, 'jardinería', 'arcilloso', 'prados: false, campos: false, jardines: true, costa: false, interior: false, montaña: false')
    insertRow(39, 'Magnolia', 'La magnolia es un árbol perenne de la familia de las magnoliáceas. Tiene flores grandes y vistosas y se utiliza en jardinería y paisajismo.', 'Tiene flores grandes y vistosas y se utiliza en jardinería y paisajismo.', '/imagenes/plantas/magnolia.png', False, False, True, 'jardinería', 'arcilloso', 'prados: false, campos: false, jardines: true, costa: false, interior: false, montaña: false')
    insertRow(40, 'Fresno', 'El fresno es un árbol caducifolio de la familia de las oleáceas. Tiene hojas compuestas y se utiliza en carpintería y ebanistería.', 'Tiene hojas compuestas y se utiliza en carpintería y ebanistería.', '/imagenes/plantas/fresno.png', False, True, False, 'carpintería', 'arcilloso', 'prados: false, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(41, 'Ficus', 'El ficus es un árbol perenne de la familia de las moráceas. Tiene hojas grandes y se utiliza en jardinería y decoración interior.', 'Tiene hojas grandes y se utiliza en jardinería y decoración interior.', '/imagenes/plantas/ficus.png', False, False, True, 'jardinería', 'arcilloso', 'prados: false, campos: false, jardines: true, costa: false, interior: true, montaña: false')
    insertRow(42, 'Cactus', 'El cactus es una planta suculenta de la familia de las cactáceas. Tiene tallos carnosos y se utiliza en jardinería y decoración.', 'Tiene tallos carnosos y se utiliza en jardinería y decoración.', '/imagenes/plantas/cactus.png', False, False, True, 'jardinería', 'arenoso', 'prados: false, campos: false, jardines: true, costa: false, interior: true, montaña: false')
    insertRow(43, 'Eucalipto', 'El eucalipto es un árbol perenne de la familia de las mirtáceas. Tiene hojas lanceoladas y se utiliza en carpintería y medicina.', 'Tiene hojas lanceoladas y se utiliza en carpintería y medicina.', '/imagenes/plantas/eucalipto.png', False, False, True, 'carpintería', 'arenoso', 'prados: false, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(44, 'Ciprés', 'El ciprés es un árbol perenne de la familia de las cupresáceas. Tiene hojas escamosas y se utiliza en jardinería y paisajismo.', 'Tiene hojas escamosas y se utiliza en jardinería y paisajismo.', '/imagenes/plantas/cipres.png', False, False, False, 'jardinería', 'arenoso', 'prados: false, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(45, 'Bambú', 'El bambú es una planta leñosa de la familia de las poáceas. Tiene tallos largos y flexibles y se utiliza en construcción y artesanía.', 'Tiene tallos largos y flexibles y se utiliza en construcción y artesanía.', '/imagenes/plantas/bambu.png', False, False, True, 'construcción', 'arenoso', 'prados: false, campos: false, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(46, 'Caña', 'La caña es una planta herbácea de la familia de las poáceas. Tiene tallos huecos y se utiliza en construcción y artesanía.', 'Tiene tallos huecos y se utiliza en construcción y artesanía.', '/imagenes/plantas/cana.png', False, False, False, 'construcción', 'arcilloso', 'prados: false, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(47, 'Laurel', 'El laurel es un arbusto perenne de la familia de las lauráceas. Tiene hojas lanceoladas y se utiliza en gastronomía y medicina.', 'Tiene hojas lanceoladas y se utiliza en gastronomía y medicina.', '/imagenes/plantas/laurel.png', False, False, False, 'gastronomía', 'arcilloso', 'prados: false, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(48, 'Begonia', 'La begonia es una planta ornamental de la familia de las begoniáceas. Tiene flores llamativas y se utiliza en jardinería y decoración interior.', 'Tiene flores llamativas y se utiliza en jardinería y decoración interior.', '/imagenes/plantas/begonia.png', False, False, True, 'jardinería', 'arcilloso', 'prados: false, campos: false, jardines: true, costa: false, interior: true, montaña: false')
    insertRow(49, 'Orquídea', 'La orquídea es una planta epífita de la familia de las orquidáceas. Tiene flores exóticas y se utiliza en jardinería y floristería.', 'Tiene flores exóticas y se utiliza en jardinería y floristería.', '/imagenes/plantas/orquidea.png', False, False, True, 'jardinería', 'arcilloso', 'prados: false, campos: false, jardines: true, costa: false, interior: true, montaña: false')
    insertRow(50, 'Tradescantia Fluminensis', 'La Tradescantia fluminensis es una planta perenne de la familia Commelinaceae. Tiene hojas verdes y se utiliza en jardinería y paisajismo.', 'Tiene hojas verdes y se utiliza en jardinería y paisajismo.', '/imagenes/plantas/tradescantia-fluminensis.png', False, False, True, 'jardinería', 'arcilloso', 'prados: false, campos: false, jardines: true, costa: true, interior: true, montaña: false')
    insertRow(51, 'Tomillo', 'El tomillo es un arbusto aromático de la familia de las lamiáceas. Tiene hojas pequeñas y se utiliza en gastronomía y medicina.', 'Tiene hojas pequeñas y se utiliza en gastronomía y medicina.', '/imagenes/plantas/tomillo.png', False, True, False, 'gastronomía', 'arcilloso', 'prados: false, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(52, 'Almendro', 'El almendro es un árbol caducifolio de la familia de las rosáceas. Tiene frutos comestibles y se utiliza en agricultura y repostería.', 'Tiene frutos comestibles y se utiliza en agricultura y repostería.', '/imagenes/plantas/almendro.png', False, False, False, 'agricultura', 'arcilloso', 'prados: false, campos: true, jardines: true, costa: false, interior: true, montaña: true')
    insertRow(53, 'Nogal', 'El nogal es un árbol caducifolio de la familia de las juglandáceas. Tiene frutos comestibles y se utiliza en carpintería y alimentación.', 'Tiene frutos comestibles y se utiliza en carpintería y alimentación.', '/imagenes/plantas/nogal.png', False, False, False, 'carpintería', 'arcilloso', 'prados: false, campos: true, jardines: true, costa: false, interior: true, montaña: true')
    insertRow(54, 'Cedro', 'El cedro es un árbol perenne de la familia de las pináceas. Tiene madera aromática y se utiliza en carpintería y construcción.', 'Tiene madera aromática y se utiliza en carpintería y construcción.', '/imagenes/plantas/cedro.png', False, False, True, 'carpintería', 'arcilloso', 'prados: false, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(55, 'Abeto', 'El abeto es un árbol perenne de la familia de las pináceas. Tiene hojas aciculares y se utiliza en carpintería y decoración.', 'Tiene hojas aciculares y se utiliza en carpintería y decoración.', '/imagenes/plantas/abeto.png', False, False, True, 'carpintería', 'arcilloso', 'prados: false, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(56, 'Narciso', 'El narciso es una planta bulbosa de la familia de las amarilidáceas. Tiene flores perfumadas y se utiliza en jardinería y floristería.', 'Tiene flores perfumadas y se utiliza en jardinería y floristería.', '/imagenes/plantas/narciso.png', False, False, False, 'jardinería', 'arcilloso', 'prados: false, campos: false, jardines: true, costa: false, interior: true, montaña: true')
    insertRow(57, 'Hiedra', 'La hiedra es una planta trepadora de la familia de las araliáceas. Tiene hojas perennes y se utiliza en jardinería y paisajismo.', 'Tiene hojas perennes y se utiliza en jardinería y paisajismo.', '/imagenes/plantas/hiedra.png', False, False, False, 'jardinería', 'arcilloso', 'prados: false, campos: false, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(58, 'Violeta', 'La violeta es una planta herbácea de la familia de las violáceas. Tiene flores coloridas y se utiliza en jardinería y perfumería.', 'Tiene flores coloridas y se utiliza en jardinería y perfumería.', '/imagenes/plantas/violeta.png', False, True, False, 'jardinería', 'arcilloso', 'prados: false, campos: true, jardines: true, costa: false, interior: true, montaña: true')
    insertRow(59, 'Amapola', 'La amapola es una planta herbácea de la familia de las papaveráceas. Tiene flores vistosas y se utiliza en jardinería y medicina.', 'Tiene flores vistosas y se utiliza en jardinería y medicina.', '/imagenes/plantas/amapola.png', False, True, False, 'jardinería', 'arcilloso', 'prados: false, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(60, 'Encina', 'La encina es un árbol perenne de la familia de las fagáceas. Tiene hojas coriáceas y se utiliza en ganadería y leña.', 'Tiene hojas coriáceas y se utiliza en ganadería y leña.', '/imagenes/plantas/encina.png', False, True, False, 'ganadería', 'arcilloso', 'prados: false, campos: true, jardines: false, costa: false, interior: true, montaña: true')
    insertRow(61, 'Ortiga', 'La ortiga es una planta herbácea de la familia de las urticáceas. Tiene hojas urticantes y se utiliza en medicina y alimentación.', 'Tiene hojas urticantes y se utiliza en medicina y alimentación.', '/imagenes/plantas/ortiga.png', False, True, False, 'medicina', 'arcilloso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(62, 'Hinojo Silvestre', 'El hinojo silvestre es una planta herbácea de la familia de las apiáceas. Tiene hojas aromáticas y se utiliza en gastronomía y medicina.', 'Tiene hojas aromáticas y se utiliza en gastronomía y medicina.', '/imagenes/plantas/hinojo-silvestre.png', False, True, False, 'gastronomía', 'arcilloso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(63, 'Cebada', 'La cebada es una planta herbácea de la familia de las poáceas. Tiene granos comestibles y se utiliza en agricultura y alimentación.', 'Tiene granos comestibles y se utiliza en agricultura y alimentación.', '/imagenes/plantas/cebada.png', False, False, False, 'agricultura', 'arcilloso', 'prados: false, campos: true, jardines: false, costa: false, interior: true, montaña: true')
    insertRow(64, 'Avena', 'La avena es una planta herbácea de la familia de las poáceas. Tiene granos comestibles y se utiliza en agricultura y alimentación.', 'Tiene granos comestibles y se utiliza en agricultura y alimentación.', '/imagenes/plantas/avena.png', False, False, False, 'agricultura', 'arcilloso', 'prados: false, campos: true, jardines: false, costa: false, interior: true, montaña: true')
    insertRow(65, 'Hinojo de Mar', 'El hinojo de mar es una planta acuática de la familia de las apiáceas. Tiene hojas aromáticas y se utiliza en gastronomía y medicina.', 'Tiene hojas aromáticas y se utiliza en gastronomía y medicina.', '/imagenes/plantas/hinojo-mar.png', False, True, False, 'gastronomía', 'arcilloso', 'prados: false, campos: false, jardines: false, costa: true, interior: false, montaña: false')
    insertRow(66, 'Cola de Caballo', 'La cola de caballo es una planta herbácea de la familia de las equisetáceas. Tiene tallos estriados y se utiliza en medicina y jardinería.', 'Tiene tallos estriados y se utiliza en medicina y jardinería.', '/imagenes/plantas/cola-caballo.png', False, True, False, 'medicina', 'arcilloso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(67, 'Alfalfa', 'La alfalfa es una planta herbácea de la familia de las fabáceas. Tiene hojas trifoliadas y se utiliza en agricultura y alimentación animal.', 'Tiene hojas trifoliadas y se utiliza en agricultura y alimentación animal.', '/imagenes/plantas/alfalfa.png', False, False, False, 'agricultura', 'arcilloso', 'prados: true, campos: true, jardines: false, costa: false, interior: true, montaña: true')
    insertRow(68, 'Fallopia Japonica', 'La Fallopia japonica es una planta perenne invasora de la familia Polygonaceae. Tiene hojas grandes y se utiliza en jardinería y medicina alternativa.', 'Tiene hojas grandes y se utiliza en jardinería y medicina alternativa.', '/imagenes/plantas/fallopia-japonica.png', True, False, False, 'jardinería', 'arcilloso', 'prados: false, campos: false, jardines: true, costa: false, interior: true, montaña: true')
    insertRow(69, 'Cotula Coronopifolia', 'La Cotula coronopifolia es una planta herbácea de la familia Asteraceae. Tiene hojas pequeñas y se utiliza en jardinería y paisajismo.', 'Tiene hojas pequeñas y se utiliza en jardinería y paisajismo.', '/imagenes/plantas/cotula-coronopifolia.png', False, False, True, 'jardinería', 'arcilloso', 'prados: false, campos: false, jardines: true, costa: true, interior: true, montaña: false')
    insertRow(70, 'Caléndula', 'La caléndula es una planta herbácea de la familia de las asteráceas. Tiene flores de color anaranjado y se utiliza en medicina y jardinería.', 'Tiene flores de color anaranjado y se utiliza en medicina y jardinería.', '/imagenes/plantas/calendula.png', False, False, False, 'medicina', 'arcilloso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
    insertRow(71, 'Trébol Blanco', 'El trébol blanco es una planta herbácea de la familia de las fabáceas. Tiene flores blancas y se utiliza en agricultura y jardinería.', 'Tiene flores blancas y se utiliza en agricultura y jardinería.', '/imagenes/plantas/trebol-blanco.png', False, False, False, 'agricultura', 'arcilloso', 'prados: true, campos: true, jardines: true, costa: true, interior: true, montaña: true')
